# Generated by Django 5.2.6 on 2025-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuruStay', '0002_remove_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
